spring.application.name=pokerService

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://mongo:27017/dataDB}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin123}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}

server.port=8085
